name: DEPLOYING BACKEND

on: 
  pull_request:
    types: [closed]
    branches:
      -develop

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: develop
            - uses: actions/setup-node@v1
              with:
                node-version: '16'
                  
            - run: npm install
            - run: npm run bundle
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'deploy/'
                  REMOTE_HOST: "ec2-54-91-7-9.compute-1.amazonaws.com"
                  REMOTE_USER: ubuntu
                  TARGET: 'nodeapps/survey-backend'
            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              env:
                NAME: 'Root'
              with:
                hosts: 'ubuntu@ec2-54-91-7-9.compute-1.amazonaws.com'
                privateKey: ${{ secrets.SERVER_SSH_KEY }}
                debug: false
                command: |
                 cd nodeapps/survey-backend
                 npm install
                 sudo systemctl stop course-backend
                 sudo cp course-backend.service /lib/systemd/system/course-backend.service
                 sudo systemctl daemon-reload
                 sudo systemctl start course-backend
